# For development at http://svn/, assuming local scripts build and libs install, and hosts file record for svn
# Install libs: http://svn/repos-web/lib/smarty/install.php
# or: docker-compose exec rweb php /opt/rweb/repos-web/lib/smarty/install.php
# Unit tests:
# docker-compose exec rweb php /opt/rweb/repos-web/lib/simpletest/install.php
# http://svn/repos-web/conf/repos.properties.test.php
version: '2.1'
services:
  svn:
    # https://github.com/Reposoft/docker-svn
    image: solsson/rweb-httpd
    expose:
      - "80"
    ports:
      - "80:80"
    environment:
      ADMIN_REST_ACCESS: "true"
    entrypoint:
      - /bin/sh
      - -c
    command:
      - >
        [ ! -d /svn/test ] && repocreate test -o daemon
        ;
        [ ! -f /svn/authz ] && echo '[/]' >> /svn/authz && echo '* = rw' >> /svn/authz
        ;
        echo '[/qa/readonly]' >> /svn/authz && echo '* = r' >> /svn/authz
        ;
        httpd
        -DFOREGROUND
        -DRWEB=fpm
        -DAUTHN=anon
        -DAUTHZ=svn
    volumes:
      - .:/opt/rweb
  rweb:
    # https://github.com/Reposoft/docker-svn
    image: solsson/rweb
    expose:
      - "9000"
    links:
      - svn:svn
    environment:
      REPOS_DOWNLOAD_RULE: "|^/svn/[^/]+/downloadableDirs/.+|"
    volumes:
      - .:/opt/rweb
