# For development at http://svn/, assuming local scripts build and libs install, and hosts file record for svn
# Image builds see https://github.com/Reposoft/docker-svn
# Create repo: docker-compose exec svn repocreate test -o daemon
# Install libs: http://svn/repos-web/lib/smarty/install.php
# or: docker-compose exec rweb php /opt/rweb/repos-web/lib/smarty/install.php
# Unit tests:
# docker-compose exec rweb php /opt/rweb/repos-web/lib/simpletest/install.php
# http://svn/repos-web/conf/repos.properties.test.php
version: '2.1'
services:
  svn:
    image: solsson/rweb-httpd:1.6.4@sha256:ea15cc8e7826af8e81fd675707381cc2148524d839fbcda2376a452361cc942d
    expose:
      - "80"
    ports:
      - "80:80"
    environment:
      ADMIN_REST_ACCESS: "true"
      AUTHN: "anon"
    volumes:
      - .:/opt/rweb
  rweb:
    image: solsson/rweb:1.6.4@sha256:fe32cc82f675d447ffb4f4a7a03fe9a62a83097eda5097dded6134c6ecba46b9
    expose:
      - "9000"
    links:
      - svn:svn
    environment:
      REPOS_DOWNLOAD_RULE: "|^/svn/[^/]+/downloadableDirs/.+|"
    volumes:
      - .:/opt/rweb
