# For development at http://svn/, assuming local scripts build and libs install
#   and /etc/hosts file record for 127.0.0.1 svn
# Image builds see https://github.com/Reposoft/docker-svn
# Create repo: docker exec -ti rweb_svn_1 repocreate test -o daemon
# Install libs: http://svn/repos-web/lib/smarty/install.php
# or: docker exec -ti rweb_rweb_1 php /opt/rweb/repos-web/lib/smarty/install.php
# Unit tests:
# docker-compose exec rweb php /opt/rweb/repos-web/lib/simpletest/install.php
# http://svn/repos-web/conf/repos.properties.test.php
version: '2.1'
services:
  svn:
    image: docker.io/solsson/svn-httpd:${REPOSOFT_DOCKERSVN_TAG:-latest}
    expose:
      - "80"
    ports:
      - "80:80"
    command:
      - -DADMIN_REST_ACCESS=true
      - -DRWEB=fpm
      - -DAUTHN=anon
    volumes:
      - .:/opt/rweb
  rweb:
    image: docker.io/solsson/fpm-rweb:${REPOSOFT_DOCKERSVN_TAG:-latest}
    expose:
      - "9000"
    links:
      - svn:svn
    environment:
      REPOS_DOWNLOAD_RULE: "|^/svn/[^/]+/downloadableDirs/.+|"
    volumes:
      - .:/opt/rweb
  releaser:
    build: ./releaser
    volumes:
    - .:/opt/rweb
    command:
    - /bin/bash
    - -cex
    - |
      cd /opt/rweb
      VERSION=${RELEASE_VERSION:?err}
      rm -Rf target
      mkdir target
      cp -r repos-plugins target/
      cp -r repos-web target/
      sed -i "s|[\x24]Rev[\x24]|$$VERSION|g" target/repos-web/view/repos.xsl
      ! diff -u repos-web/view/repos.xsl target/repos-web/view/repos.xsl
      php target/repos-web/lib/smarty/install.php
      php target/repos-web/lib/simpletest/install.php
      cd target/repos-plugins/highlight/ && npm install --ignore-scripts && ./node_modules/.bin/webpack --bail && rm -Rf node_modules && cd ../../../
      cd target/repos-web/scripts/ && ./build-defaultexcludes.bat && cd ../../../
      cd target && tar cfz ../ReposWeb-$$VERSION.tgz repos-web/ repos-plugins/ && cd ..
      cd target && zip -qr ../ReposWeb-$$VERSION.zip repos-web/ repos-plugins/ && cd ..
