# For development at http://svn/, assuming local scripts build and libs install, and hosts file record for svn
# Image builds see https://github.com/Reposoft/docker-svn
# Create repo: docker-compose exec svn repocreate test -o daemon
# Install libs: http://svn/repos-web/lib/smarty/install.php
# or: docker-compose exec rweb php /opt/rweb/repos-web/lib/smarty/install.php
# Unit tests:
# docker-compose exec rweb php /opt/rweb/repos-web/lib/simpletest/install.php
# http://svn/repos-web/conf/repos.properties.test.php
version: '2.1'
services:
  svn:
    image: solsson/rweb-httpd:1.7.1@sha256:80fba5dd8581f30302b8c6a98c4440ec8c1adb10ef59fa3b841e11b45db8a6a4
    expose:
      - "80"
    ports:
      - "80:80"
    environment:
      ADMIN_REST_ACCESS: "true"
      AUTHN: "anon"
    volumes:
      - .:/opt/rweb
  rweb:
    image: solsson/rweb:1.7.1@sha256:72f18e6829d223454213901d5b57d728c4a4528e673d5330a36e441b4dc7202e
    expose:
      - "9000"
    links:
      - svn:svn
    environment:
      REPOS_DOWNLOAD_RULE: "|^/svn/[^/]+/downloadableDirs/.+|"
    volumes:
      - .:/opt/rweb
