# For development at http://svn/, assuming local scripts build and libs install, and hosts file record for svn
# Image builds see https://github.com/Reposoft/docker-svn
# Create repo: docker-compose exec svn repocreate test -o daemon
# Install libs: http://svn/repos-web/lib/smarty/install.php
# or: docker-compose exec rweb php /opt/rweb/repos-web/lib/smarty/install.php
# Unit tests:
# docker-compose exec rweb php /opt/rweb/repos-web/lib/simpletest/install.php
# http://svn/repos-web/conf/repos.properties.test.php
version: '2.1'
services:
  svn:
    image: solsson/rweb-httpd:1.7.3@sha256:dcc26dca1a52864ac1fbe94b8433b8af85768b9f24339342bc98e7f4d03ebb41
    expose:
      - "80"
    ports:
      - "80:80"
    environment:
      ADMIN_REST_ACCESS: "true"
      AUTHN: "anon"
    volumes:
      - .:/opt/rweb
  rweb:
    image: solsson/rweb:1.7.3@sha256:94353fbcea1ea10304d42cc8cae85b33a9b6108a10988c3badada1649473584a
    expose:
      - "9000"
    links:
      - svn:svn
    environment:
      REPOS_DOWNLOAD_RULE: "|^/svn/[^/]+/downloadableDirs/.+|"
    volumes:
      - .:/opt/rweb
