# For development at http://svn/, assuming local scripts build and libs install, and hosts file record for svn
# Image builds see https://github.com/Reposoft/docker-svn
# Create repo: docker-compose exec svn repocreate test -o daemon
# Install libs: http://svn/repos-web/lib/smarty/install.php
version: '2.1'
services:
  svn:
    image: solsson/rweb-httpd@sha256:4a0661e12da2ef4cc5dfbff08213a28b628bd522c85607e26e3425e30310821b
    expose:
      - "80"
    ports:
      - "80:80"
    environment:
      ADMIN_REST_ACCESS: "true"
      AUTHN: "anon"
    volumes:
      - .:/opt/rweb
  rweb:
    image: solsson/rweb@sha256:63de4e9d4469ef3dc05d88793fbbcb52329bdf3c21f35928cca8685b43f7f9b5
    expose:
      - "9000"
    links:
      - svn:svn
    volumes:
      - .:/opt/rweb
