#!/bin/bash

FROM="16x16"

# copy selected icons to where they are needed for the webapp
# commandbar
TO="../commands"
cp "$FROM/actions/up.png" "$TO/_parent.png"
cp "$FROM/actions/attach.png" "$TO/_upload.png"
cp "$FROM/actions/messagebox_info.png" "$TO/_log.png"
cp "$FROM/filesystems/folder_whitelinen_open.png" "$TO/_newfolder.png"
cp "$FROM/filesystems/folder_sharkskin_open.png" "$TO/_windowsfolder.png"
cp "$FROM/filesystems/folder_applegreen_open.png" "$TO/_tortoisefolder.png"
cp "$FROM/filesystems/folder_banana.png" "$TO/_folder.png"
cp "$FROM/mimetypes/mime.png" "$TO/_file.png"
cp "$FROM/actions/stop.png" "$TO/_logout.png"
cp "$FROM/actions/stop.png" "$TO/_logout.png"
cp "$FROM/actions/leftjust.png" "$TO/_simple.png"
cp "$FROM/actions/textblock.png" "$TO/_detailed.png"
#  filetypes
TO="../repository/filetypes"
cp "$FROM/mimetypes/archive_zip.png" "$TO/zip.png"
cp "$FROM/mimetypes/archive_gz.png" "$TO/gz.png"
cp "$FROM/mimetypes/archive_sit.png" "$TO/sit.png"
cp "$FROM/mimetypes/chm.png" "$TO/chm.png"
cp "$FROM/mimetypes/exec_wine.png" "$TO/exe.png"
cp "$FROM/mimetypes/html.png" "$TO/html.png"
cp "$FROM/mimetypes/html.png" "$TO/htm.png"
cp "$FROM/mimetypes/msword_doc.png" "$TO/doc.png"
cp "$FROM/mimetypes/image_ai.png" "$TO/ai.png"
cp "$FROM/mimetypes/image_bmp.png" "$TO/bmp.png"
cp "$FROM/mimetypes/image_gif.png" "$TO/gif.png"
cp "$FROM/mimetypes/image_jpeg.png" "$TO/jpg.png"
cp "$FROM/mimetypes/image_png.png" "$TO/png.png"
cp "$FROM/mimetypes/image_psd.png" "$TO/psd.png"
cp "$FROM/mimetypes/image_tiff.png" "$TO/tif.png"
cp "$FROM/mimetypes/library.png" "$TO/jar.png"
cp "$FROM/mimetypes/log.png" "$TO/log.png"
cp "$FROM/mimetypes/pdf.png" "$TO/pdf.png"
cp "$FROM/mimetypes/postscript.png" "$TO/ps.png"
cp "$FROM/mimetypes/quicktime.png" "$TO/qt.png"
cp "$FROM/mimetypes/shellscript.png" "$TO/sh.png"
cp "$FROM/mimetypes/source_java.png" "$TO/java.png"
cp "$FROM/mimetypes/source_php.png" "$TO/php.png"
cp "$FROM/mimetypes/temp.png" "$TO/tmp.png"
cp "$FROM/mimetypes/txt.png" "$TO/txt.png"
cp "$FROM/mimetypes/vcalendar.png" "$TO/ics.png"
cp "$FROM/mimetypes/vcard.png" "$TO/vcf.png"
cp "$FROM/mimetypes/video.png" "$TO/mpg.png"
cp "$FROM/mimetypes/ooo_sxw.png" "$TO/sxw.png"
#    log
TO="../log"
cp "$FROM/actions/2leftarrow.png" "$TO/_copiedfrom.png"
cp "$FROM/actions/fileopen.png" "$TO/_m.png"
cp "$FROM/actions/attach.png" "$TO/_a.png"
cp "$FROM/actions/textblock.png" "$TO/_message.png"
cp "$FROM/apps/db.png" "$TO/_d.png"

